Repository MicrosoftDocs/azure-docs.it-it, pull requests merged in 2019-06, with the labels that each got.

#281 Fix typo
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: In Progress

#279 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#280 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#282 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted, Linguistic Suggestion

#283 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#284 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#285 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#286 Update reference-connect-sync-attributes-synchronized.md
  articles/active-directory/hybrid/reference-connect-sync-attributes-synchronized.md
Labels: Accepted, Linguistic Suggestion

#287 Fix mistranslation
  articles/digital-twins/how-to-egress-endpoints.md
Labels: Accepted, Linguistic Suggestion

#290 Fix mistranslation
  articles/event-grid/event-schema-container-registry.md
Labels: Accepted, Linguistic Suggestion

#289 Fix mistranslation
  articles/event-grid/event-schema-blob-storage.md
Labels: Accepted, Linguistic Suggestion

#288 Fix mistranslation
  articles/event-grid/event-schema-azure-maps.md
Labels: Accepted, Linguistic Suggestion

#294 Fix mistranslation
  articles/event-grid/event-schema-service-bus.md
Labels: In Progress

#293 Fix mistranslation
  articles/event-grid/event-schema-resource-groups.md
Labels: In Progress

#292 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: In Progress

#291 Fix mistranslation
  articles/event-grid/event-schema-event-hubs.md
Labels: In Progress

#297 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#296 Fix mistranslation
  articles/event-grid/event-schema.md
Labels: In Progress

#295 Fix mistranslation
  articles/event-grid/event-schema-subscriptions.md
Labels: In Progress

#298 Fix mistranslation
  articles/lab-services/devtest-lab-artifact-author.md
Labels: In Progress

#299 Fix mistranslation
  articles/logic-apps/logic-apps-custom-api-authentication.md
Labels: In Progress

#300 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#301 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#303 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#304 Fix mistranslation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: In Progress

#307 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-windows.md
Labels: In Progress

#306 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-linux.md
Labels: In Progress

#305 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: In Progress

#308 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-windows.md
Labels: In Progress

#309 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: In Progress

#310 Fix mistranslation
  articles/virtual-machines/extensions/dsc-template.md
Labels: Accepted

#312 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-linux.md
Labels: Accepted, Linguistic Suggestion

#311 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: In Progress, Linguistic Suggestion

#316 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: In Progress

#315 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: In Progress

#314 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-blob-connector.md
Labels: In Progress

#319 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#317 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: In Progress

#318 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: In Progress

#320 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#321 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-definition-language.md
Labels: Accepted, Linguistic Suggestion

#322 Fix mistranslation
  articles/logic-apps/workflow-definition-language-functions-reference.md
Labels: Accepted

#323 Fix mistranslation
  articles/media-services/latest/media-services-event-schemas.md
Labels: Accepted, Linguistic Suggestion

#324 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#325 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted

#327 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted, Linguistic Suggestion

#326 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#328 Fix mistranslation
  articles/azure-monitor/insights/solutions-solution-file.md
Labels: Accepted, Linguistic Suggestion

#329 Fix mistranslation
  articles/azure-monitor/log-query/unify-app-resource-data.md
Labels: Accepted

#330 Fix mistranslation
  articles/azure-monitor/platform/activity-log-export.md
Labels: Accepted

#331 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted
