Repository MicrosoftDocs/azure-docs.it-it, pull requests merged in 2019-05, with the labels that each got.

#229 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, In Progress

#230 Fix mistranslation
  articles/azure-functions/functions-reference-node.md
Labels: Accepted, In Progress

#231 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, In Progress

#232 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, In Progress

#233 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, In Progress

#234 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted, In Progress

#235 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, In Progress

#236 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: In Progress

#237 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted, In Progress

#238 Fix mistranslation
  articles/data-factory/connector-cassandra.md
Labels: Accepted, In Progress

#239 Fix mistranslation
  articles/data-factory/connector-db2.md
Labels: Accepted, In Progress

#240 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted, In Progress

#241 Fix mistranslation
  articles/data-factory/connector-ftp.md
Labels: Accepted, In Progress

#244 Fix mistranslation
  articles/data-factory/connector-hdfs.md
Labels: Accepted, In Progress

#245 Fix mistranslation
  articles/data-factory/connector-http.md
Labels: Accepted, In Progress

#246 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, In Progress

#242 "does not" missed in translation
  articles/aks/operator-best-practices-cluster-security.md
Labels: Accepted, Linguistic Suggestion

#247 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted, In Progress

#248 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted, In Progress

#249 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted, In Progress

#250 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, In Progress

#251 Fix mistranslation
  articles/data-factory/connector-sap-ecc.md
Labels: Accepted, In Progress

#253 Fix mistranslation
  articles/data-factory/connector-sftp.md
Labels: Accepted, In Progress

#252 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, In Progress

#254 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress

#256 Fix mistranslation
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Linguistic Suggestion

#255 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted, Linguistic Suggestion

#257 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#258 Fix mistranslation
  articles/data-factory/monitor-using-azure-monitor.md
Labels: Accepted, Linguistic Suggestion

#259 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: Accepted, Linguistic Suggestion

#260 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-powershell.md
Labels: Accepted, Linguistic Suggestion

#261 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-rest-api.md
Labels: Accepted, In Progress

#262 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-azure-portal.md
Labels: Accepted, In Progress

#263 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-powershell.md
Labels: Accepted, In Progress

#264 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-rest-api.md
Labels: Accepted, In Progress

#265 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-visual-studio.md
Labels: Accepted, In Progress

#266 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, In Progress

#269 Fix mistranslation
  articles/data-factory/v1/data-factory-hdfs-connector.md
Labels: Accepted, Linguistic Suggestion

#267 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#268 Fix mistranslation
  articles/data-factory/v1/data-factory-ftp-connector.md
Labels: Accepted, Linguistic Suggestion

#270 Fix mistranslation
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted, Linguistic Suggestion

#271 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted, Linguistic Suggestion

#272 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#273 Fix mistranslation
  articles/data-factory/v1/data-factory-map-reduce.md
Labels: Accepted, Linguistic Suggestion

#274 Fix mistranslation
  articles/data-factory/v1/data-factory-odbc-connector.md
Labels: Accepted, Linguistic Suggestion

#276 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, In Progress

#277 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-file-system-connector.md
Labels: Accepted, In Progress

#278 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted, In Progress
